# Generated by Django 4.2.3 on 2023-08-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_person_alter_myself_options_passport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='pass_id',
            new_name='pass_number',
        ),
    ]
